import { useEffect, useState } from 'react';
import TopHeader from '../components/TopHeader';
import { getProgressSummary } from '../services/api';

export default function Progress() {
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { getProgressSummary().then(setSummary).catch((err) => setError(err.message)); }, []);
  return <div className="page-card"><TopHeader eyebrow="Your momentum" title="Progress" description="Small consistent actions become visible progress." />{error && <p className="error">{error}</p>}{summary ? <><div className="progress-stat-grid"><div className="metric-card"><span>Workouts logged</span><strong>{summary.workouts_logged}</strong><small>Your recent training sessions</small></div><div className="metric-card"><span>Adherence</span><strong>{summary.adherence_percentage}%</strong><small>Completed sessions</small></div><div className="metric-card"><span>Average completion</span><strong>{summary.average_completion}%</strong><small>How much you finish</small></div></div><section className="panel chart-panel"><div className="section-heading"><div><p className="summary-label">Readiness history</p><h2>Your recent check-ins</h2></div><span className="status-pill">Personal</span></div>{summary.readiness_history.length ? <div className="readiness-bars">{summary.readiness_history.slice(0, 7).reverse().map((item, index) => <div className="readiness-bar-item" key={`${item.created_at}-${index}`}><div className={`readiness-bar ${item.readiness_level?.toLowerCase()}`} style={{ height: `${Math.max(18, Math.min(100, Number(item.score || 0)))}%` }} /><span>{item.readiness_level}</span></div>)}</div> : <div className="empty-state">Complete more Daily Checks to see your readiness pattern.</div>}</section><section className="panel"><h2>Recent feedback</h2>{summary.feedback.length ? <div className="feedback-list">{summary.feedback.slice(0, 5).map((item) => <div className="feedback-row" key={item.id}><span>{item.completion_status}</span><strong>{item.completion_percentage}%</strong><small>{item.difficulty}</small></div>)}</div> : <div className="empty-state">Finish a workout and rate it to start tracking adherence.</div>}</section></> : !error && <div className="empty-state">Loading your progress...</div>}</div>;
}
